### ISSUE TITLE
wont attach when there is a backdoor

### ISSUE THREAD

**Issue by sealpros** [iK4oS/backdoor.exe#4]
i check a game for a backdoor using a script it said there was one back door but when i tried attaching it did not work this is only for one game so its not a big issue but its good to know

game: https://www.roblox.com/games/5326244383/Doomspire-Brickbattle-8

![image](https://user-images.githubusercontent.com/63180261/116633540-a357ab00-a90e-11eb-8c19-409d2d707979.png)
the image that shows there are backdoors

**Comment by iK4oS** [comment]
If that script is the script that has been fired to the backdoored remote: it is clear that is wouldn't work since the script is basically nil. If the game is popular and known in Roblox there is a very small chance it is actually backdoored. People could fake it.
I also do not know what script you're using since it doesn't look similar.  It could be throwing false positives if it isn't as well designed as backdoor.exe. This has nothing related to our project.

**Comment by LolloDev5123** [comment]
Obviously it isn't related to this project, this is a backdoor.

**Comment by iK4oS** [comment]
Cry about it, blocked
